[build]
  command = "next build && next export"
  publish = "out"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[plugins]]
  package = "netlify-plugin-cache-nextjs"

[[redirects]]
from = "/_next/image*"
query = { url = ":url", w = ":width", q = ":quality" }
to = "/.netlify/functions/image?url=:url&w=:width&q=:quality"
status = 200